= Testing Conformance to IES

A command line utility that verifies how well sample data conforms to the basics of the IES ontology and the specific domain extension.  The utility is mainly provided to support the development of sample data rather than to be used in end-to-end data pipelines.  Usually we rely on `SHACL` shapes to for this.

== What it does?

Given any sample data file, it proceeds by analyzing the predicate in each statement.  For each predicate it attempts to establish the class to which the subject and the object belong.footnote:[This step requires each subject to have explicit statements asserting their classes.  We do *not* use inference for this.] 

It then inspects the `rdfs:subClassOf` hierarchies in order to ensure that the subject and object are subclasses of the expected classes as determined by the `rdfs:domain` and `rdfs:range` of the predicate.

The script additionally processes across the `ies:powertype` statements.  If it does not find a match as expected above, and if there is an `ies:powertype` in the class hierarchy it will check instances of the `ClassOfxyz` as `subClassOf` `xyz`.footnote:[We do *not* elaborate on the powertype pattern here and readers should refer to those sections in the `ies-common` documentation.]

If the predicate is not in the ontology files provided, an out of ontology warning message is issued.

== Usage

```cmd
python <PATH_TO>/data-domain-range-use.py --help
```

```poetry
poetry run domain-range-checker
```

 yields:

```
usage: data_domain_range_use.py [-h] [--new_ontology NEW_ONTOLOGY] [--upper_ontology UPPER_ONTOLOGY]
                                [--data DATA] [--results RESULTS]

Validate a data ttl graph against a new ontology together with an upper (or common) ontology.

options:
  -h, --help            show this help message and exit
  --new_ontology NEW_ONTOLOGY
                        Path to the new ontology
  --upper_ontology UPPER_ONTOLOGY
                        Path to the upper ontology
  --data DATA           Path to the data .ttl
  --results RESULTS     Path to the results directory
```

== Results

The script produces two output files:

`data_validation.ttl` 

This file follows the `shacl` tradition of providing results in the form of a graph.  Output is divided as follows:

- Summary that differentiates between errors and warnings.  If the predicate-object `conforms true` appear in the summary, it means that there are no discernable errors.  As illustrated below:

```
[] a :DataValidationReport ;
    :conforms true ;
    :numberOfWarnings 1 .
```

- Each error is listed and calls out the expected class and the actual class.  For example,

```
[] a :DomainError ;
    :actualDomain "http://ies.data.gov.uk/ontology/ies-building1#MoneyTransferEstimate" ;
    :expectedDomain "http://ies.data.gov.uk/ontology/ies4#Assessment" ;
    :object <http://example.com/HeatingCost_b11> ;
    :predicate <http://ies.data.gov.uk/ontology/ies4#assessed> ;
    :reason "no subClass or powertype" ;
    :subject <http://example.com/GBP_ES_4a3> .
```

Here we have a situation where there is a `:DomainError` on a statement that uses the predicate `ies:assessed`, it has a subject that is an instance of the class `building:MoneyTransferEstimate`, but `ies:assessed` has a domain of `ies:Assessment`.

The `:RangeError` has the same format but on the range of the predicate (ie the object of the statement)

In addition to the validation graph there is `verbose-data-validation.txt`.  This text file gives a terse but complete listing of every statement tested.  It is really only useful in detailed debugging.


