= Mustrd Sparql Unit Tests

Mustrd is an open source utility available on https://pypi.org/project/mustrd/[PyPi] which can help

- setup data scenarios and ensure sparql queries work as expected

- setup edge cases for queries and ensure they still work

- isolate small sparql enrichment / transformation steps and know we're only INSERTing what we intend

We provide instructions on how to use and run mustrd without the need to install it.

== A Basic Mustrd Specification

A test consists of a specification in ttl, or trig files. We use the specification by example (SBE) approach of Given, When, Then to define starting dataset, an action, and a set of expectations. So, GIVEN data and ontologies, WHEN we run the Sparql query, THEN these results are expected.

In the course of developing the ontologies we translate a number of competency questions into Sparql queries.  We then apply these to our sample data and combined ontology in order to be able to test the result.

A skeleton is shown below:

```turtle
@prefix must: <https://mustrd.com/model/> . 
@prefix test-data: <https://ttp://ies.data.gov.uk/ontology/test/> . 
@prefix building: <http://ies.data.gov.uk/ontology/ies-building1#> . 
@prefix ies: <http://ies.data.gov.uk/ontology/ies4#> . 
@prefix ex: <http://example.com> . 

test-data:details_by_uprn
    a          must:TestSpec ;
    must:given 

    [ a must:FileDataset ;
                    must:file "data.ttl" ;
                ] ,     
#
# as many of these as necessary - usually consisting of data, eis-common, and ies-domain followed by ;
#

    must:when  [ a must:TextSparqlSource ;
                    must:queryText """
 #                   
 #                The sparql query to be tested
 #
                    """
                    must:queryType must:SelectSparql ;
                ];
    must:then [
        a must:TableDataset ;
#
#    A row and column binding format in turtle for the expected results
#        
    ] . 

```
 
So the basic format is: for *this test*; *given* data and ontologies; *when* running this query; *then* expect this result. A complete example is in the companion test file https://github.com/Semantic-partners/mustrd/blob/master/test/test-specs/select_spec.mustrd.ttl[here].  Reader should refer to the mustrd github for the complete range of data formats, sparql statements, expected result formats covered. https://github.com/Semantic-partners/mustrd/blob/master/GETSTARTED.adoc#givens[This is a good starting point to explore the variations available]footnote:[mustrd covers a much larger array of scenarios than used here in relation to competency questions represented in sparql]

*Important* each test specification in this format must have the file name ending with `.mustrd.ttl`. 

== Usage

Mustrd has some complexity between the location of the `mustrd-configuration.ttl` file and the directories that hold the specifications of the tests and the test data.  As the configuration file location is set in this template.  When using docker which is recommended, the configuration directories are relative to the mounted location of the configuration file.  A sample configuration is shown below:

```turtle
@prefix : <https://mustrd.com/mustrdTest/> .
@prefix triplestore:<https://mustrd.com/triplestore/> .

:test_example a :MustrdTest;
                :hasSpecPath "../../../tests/unit/mustrd_tests";
                :hasDataPath "../../../src/data";
                :hasPytestPath "rdflib";
                :filterOnTripleStore triplestore:RdfLib .
```

Notice how we have to go three levels up relative to the configuration file and then down to the appropriate directories.  Bear this in mind if you wish to set different directories or move the configuration file. footnote:[You are also able to use mustrd with other triple stores, but this is beyond the scope of this deployment]

The easiest way to use mustrd is to run the provided docker version as follows:

```cmd
docker run --rm -v "$(pwd):/app" mustrd/mustrd --config /app/ies-tools/src/mustrd_runner/mustrd_configuration.ttl --md /app/github_job_summary.md
```

Breakdown of the Command:

	1.	docker run --rm
	•	Runs a Docker container.
	•	--rm automatically removes the container after it finishes execution.
	2.	-v "$(pwd):/app"
	•	Mounts the current working directory ($(pwd)) into the container at /app.
	•	This allows the container to access local files.
	3.	mustrd/mustrd
	•	Uses the mustrd/mustrd Docker image.
	4.	--config /app/ies-tools/src/mustrd_runner/mustrd_configuration.ttl
	•	Specifies a configuration file (mustrd_configuration.ttl) located inside the mounted /app directory.
	5.	--md /app/github_job_summary.md
	•	Specifies an output file (github_job_summary.md), likely for a Markdown summary.

There are some *very important* points to note:

- Think of /app as the current directory and then everything in the command is tied to that

- If you change the location of the configuration file or want to use different directories for your data or tests, remember the paths in the configuration file are *relative to the location of the configuration file*.footnote:[If you are installing your own version of mustrd you are able to make the file locations absolute directories on the host computer]

- Remember to use the file name convention otherwise mustrd will not be able to find the tests.
