= Testing technical features using shacl

We recommend domain ontologies conform to some basic technical standards related to the use of standard predicates and annotation properties.

== Mandatory predicates

We regard the following as mandatory and therefore should be present in every Class and Property.

- `rdfs:comment` used to provide a definition

- `rdfs:label` relied by user interfaces and automated reports

We expect 100% conformance with these.

== Recommended

It is useful to use `skos` predicates to further elaborate on each Class and Property

- `skos:note` used to add annotations beyond the basic definition

- `skos:example` used to provide human readable examples of the Class or Property.

We simply monitor the use of these predicates and report them as the overall key performance metrics.

== Usage

```cmd
python <PATH_TO>/ontology_kpi_test_runner.py --help
```

```poetry
poetry run kpi-runner
```

yields

```
usage: kpi-runner [-h] [--kpi_directory KPI_DIRECTORY] [--new_ontology NEW_ONTOLOGY] [--results RESULTS]

Run all shacl validations in a give directory

options:
  -h, --help            show this help message and exit
  --kpi_directory KPI_DIRECTORY
                        Path to kpi directory
  --new_ontology NEW_ONTOLOGY
                        Path to the new ontology
```

We have placed the standard KPI shacl files in the KPI sub-directory.

== Results

The standard shacl results for each file in the KPI directory are written to individual result ttl files.



